### ISSUE TITLE
Target Schema Config

### ISSUE THREAD

**Issue by djamadeus** [tglunde/dbt-exasol#73]
When a specific target schema is set for a model directory in `dbt_project.yml` the schema from the profile-config is not overwriten but the values get appended:

in `.dbt/profiles`:

```
dbt-exasol:
  outputs:
    dev:
      dbname: exa_db
      dsn: exasol:8563
      password: *******
      threads: 4
      schema: TEST
      type: exasol
      user: sys
  target: dev
```

in dbt_project.yml:
````
models:
  test:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    datalake:
      +materialized: table
      +schema: DATA_LAKE

```

leads to query-generation: `Select * from TESTDATA_LAKE`
